### PR TITLE
Added the kubernetes logo

### PR DESCRIPTION
**Pull request by Debanitrkl**
Added the Kubernetes official logo for the katacoda avatar. The logo has been taken from https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png

### CODE REVIEW

**Review by MadhavJivrajani — COMMENTED** [review]
/lgtm
/hold
since it involves logo assets and wanted to make sure we're doing things the right way.
/cc @jberkus 
the logo was taken from k/community as mentioned in the PR description, if that is the right place and there's nothing else to mention/do then please remove the hold! Thank you! ❤️

**Comment by jberkus** [comment]
it's fine to use the logo this way.  It's a kubernetes community thing, working on kubernetes.

/approve
/lgtm

**Pull request merged**
